// <auto-generated>
//   Generated by tools/cascade_emit.py from cascade/tree.json.
//   Do not edit by hand.
//   Stats: depth=4 leaves=13 decided=1 purity_threshold=1.0.
// </auto-generated>
using System;

namespace Rinha.Api.Scorers;

public static class Cascade
{
    /// <summary>
    /// Pre-classifies a query before the IVF scorer. Returns (decided, score):
    ///   decided=true  → cascade committed; use the returned score directly.
    ///   decided=false → query landed in a rejected leaf; caller must fall through
    ///                   to the full IvfScorer.
    /// </summary>
    /// <param name="query">14-dim normalized query vector.</param>
    /// <param name="top3Cells">IDs of the 3 nearest IVF centroids (sorted ascending by distance).</param>
    /// <param name="top3Dists">Squared L2 distances to those 3 centroids.</param>
    public static (bool decided, float score) TryDecide(
        ReadOnlySpan<float> query,
        ReadOnlySpan<int>   top3Cells,
        ReadOnlySpan<float> top3Dists)
    {
        if (query[7] <= 0.1830768f)
        {
            if (query[2] <= 0.0738907f)
            {
                // leaf 2: n=28795 purity=1.000 pred=legit
                return (true, 0f);
            }
            else
            {
                if (top3Dists[0] <= 0.1385360f)
                {
                    if (top3Dists[0] <= 0.1302495f)
                    {
                        // leaf 5: n=252 purity=0.567 REJECT → IvfScorer fallback
                        return (false, 0f);
                    }
                    else
                    {
                        // leaf 6: n=41 purity=0.805 REJECT → IvfScorer fallback
                        return (false, 0f);
                    }
                }
                else
                {
                    if (query[7] <= 0.1166595f)
                    {
                        // leaf 8: n=429 purity=0.559 REJECT → IvfScorer fallback
                        return (false, 0f);
                    }
                    else
                    {
                        // leaf 9: n=335 purity=0.549 REJECT → IvfScorer fallback
                        return (false, 0f);
                    }
                }
            }
        }
        else
        {
            if (query[3] <= 0.2826087f)
            {
                if (query[5] <= 0.0069444f)
                {
                    if (query[0] <= 0.2001350f)
                    {
                        // leaf 13: n=20 purity=0.650 REJECT → IvfScorer fallback
                        return (false, 0f);
                    }
                    else
                    {
                        // leaf 14: n=22784 purity=1.000 REJECT → IvfScorer fallback
                        return (false, 0f);
                    }
                }
                else
                {
                    if (query[8] <= 0.2750000f)
                    {
                        // leaf 16: n=20 purity=0.750 REJECT → IvfScorer fallback
                        return (false, 0f);
                    }
                    else
                    {
                        // leaf 17: n=54 purity=0.611 REJECT → IvfScorer fallback
                        return (false, 0f);
                    }
                }
            }
            else
            {
                if ((float)top3Cells[1] <= 106.0000000f)
                {
                    if (top3Dists[2] <= 0.7867591f)
                    {
                        // leaf 20: n=686 purity=0.554 REJECT → IvfScorer fallback
                        return (false, 0f);
                    }
                    else
                    {
                        // leaf 21: n=80 purity=0.725 REJECT → IvfScorer fallback
                        return (false, 0f);
                    }
                }
                else
                {
                    if (top3Dists[1] <= 0.9609268f)
                    {
                        // leaf 23: n=583 purity=0.551 REJECT → IvfScorer fallback
                        return (false, 0f);
                    }
                    else
                    {
                        // leaf 24: n=21 purity=0.762 REJECT → IvfScorer fallback
                        return (false, 0f);
                    }
                }
            }
        }
    }
}
