// <auto-generated>
//   Generated by tools/cascade_emit.py from cascade/tree.json.
//   Do not edit by hand.
//   Stats: depth=5 leaves=22 decided=2 purity_threshold=1.0.
// </auto-generated>
using System;

namespace Rinha.Api.Scorers;

public static class Cascade
{
    /// <summary>
    /// Pre-classifies a query before the IVF scorer. Returns (decided, score):
    ///   decided=true  → cascade committed; use the returned score directly.
    ///   decided=false → query landed in a rejected leaf; caller must fall through
    ///                   to the full IvfScorer.
    /// </summary>
    /// <param name="query">14-dim normalized query vector.</param>
    /// <param name="top3Cells">IDs of the 3 nearest IVF centroids (sorted ascending by distance).</param>
    /// <param name="top3Dists">Squared L2 distances to those 3 centroids.</param>
    public static (bool decided, float score) TryDecide(
        ReadOnlySpan<float> query,
        ReadOnlySpan<int>   top3Cells,
        ReadOnlySpan<float> top3Dists)
    {
        if (query[7] <= 0.1830768f)
        {
            if (query[2] <= 0.0738907f)
            {
                // leaf 2: n=28795 purity=1.000 pred=legit
                return (true, 0f);
            }
            else
            {
                if (top3Dists[0] <= 0.1385360f)
                {
                    if (top3Dists[0] <= 0.1302495f)
                    {
                        if (query[13] <= 0.0138325f)
                        {
                            // leaf 6: n=84 purity=0.714 REJECT → IvfScorer fallback
                            return (false, 0f);
                        }
                        else
                        {
                            // leaf 7: n=168 purity=0.506 REJECT → IvfScorer fallback
                            return (false, 0f);
                        }
                    }
                    else
                    {
                        if (query[6] <= 0.1522945f)
                        {
                            // leaf 9: n=20 purity=0.700 REJECT → IvfScorer fallback
                            return (false, 0f);
                        }
                        else
                        {
                            // leaf 10: n=21 purity=0.905 REJECT → IvfScorer fallback
                            return (false, 0f);
                        }
                    }
                }
                else
                {
                    if (query[7] <= 0.1166595f)
                    {
                        if (query[12] <= 0.3250000f)
                        {
                            // leaf 13: n=178 purity=0.629 REJECT → IvfScorer fallback
                            return (false, 0f);
                        }
                        else
                        {
                            // leaf 14: n=251 purity=0.510 REJECT → IvfScorer fallback
                            return (false, 0f);
                        }
                    }
                    else
                    {
                        if (top3Dists[0] <= 0.1638474f)
                        {
                            // leaf 16: n=59 purity=0.610 REJECT → IvfScorer fallback
                            return (false, 0f);
                        }
                        else
                        {
                            // leaf 17: n=276 purity=0.583 REJECT → IvfScorer fallback
                            return (false, 0f);
                        }
                    }
                }
            }
        }
        else
        {
            if (query[3] <= 0.2826087f)
            {
                if (query[5] <= 0.0069444f)
                {
                    if (query[13] <= 0.0099985f)
                    {
                        if (query[0] <= 0.2003375f)
                        {
                            // leaf 22: n=20 purity=0.950 REJECT → IvfScorer fallback
                            return (false, 0f);
                        }
                        else
                        {
                            // leaf 23: n=22764 purity=1.000 pred=fraud
                            return (true, 1f);
                        }
                    }
                    else
                    {
                        // leaf 24: n=20 purity=0.650 REJECT → IvfScorer fallback
                        return (false, 0f);
                    }
                }
                else
                {
                    if (query[8] <= 0.2750000f)
                    {
                        // leaf 26: n=20 purity=0.750 REJECT → IvfScorer fallback
                        return (false, 0f);
                    }
                    else
                    {
                        if (query[13] <= 0.0159435f)
                        {
                            // leaf 28: n=23 purity=0.609 REJECT → IvfScorer fallback
                            return (false, 0f);
                        }
                        else
                        {
                            // leaf 29: n=31 purity=0.774 REJECT → IvfScorer fallback
                            return (false, 0f);
                        }
                    }
                }
            }
            else
            {
                if ((float)top3Cells[1] <= 106.0000000f)
                {
                    if (top3Dists[2] <= 0.7867591f)
                    {
                        if (query[0] <= 0.0574395f)
                        {
                            // leaf 33: n=29 purity=0.690 REJECT → IvfScorer fallback
                            return (false, 0f);
                        }
                        else
                        {
                            // leaf 34: n=657 purity=0.565 REJECT → IvfScorer fallback
                            return (false, 0f);
                        }
                    }
                    else
                    {
                        if (query[0] <= 0.2470425f)
                        {
                            // leaf 36: n=59 purity=0.814 REJECT → IvfScorer fallback
                            return (false, 0f);
                        }
                        else
                        {
                            // leaf 37: n=21 purity=0.524 REJECT → IvfScorer fallback
                            return (false, 0f);
                        }
                    }
                }
                else
                {
                    if (top3Dists[1] <= 0.9609268f)
                    {
                        if ((float)top3Cells[0] <= 169.0000000f)
                        {
                            // leaf 40: n=392 purity=0.584 REJECT → IvfScorer fallback
                            return (false, 0f);
                        }
                        else
                        {
                            // leaf 41: n=191 purity=0.518 REJECT → IvfScorer fallback
                            return (false, 0f);
                        }
                    }
                    else
                    {
                        // leaf 42: n=21 purity=0.762 REJECT → IvfScorer fallback
                        return (false, 0f);
                    }
                }
            }
        }
    }
}
