// <auto-generated>
// Generated by tools/train_hard_query.py — DO NOT EDIT.
// depth=4 hard_rate=4.326% hard_prec=0.905 hard_rec=1.000 f1=0.950
// </auto-generated>
namespace Rinha.Api.Scorers;

internal static class HardQueryClassifier
{
    public static bool IsHard(System.ReadOnlySpan<float> q)
    {
        if (q[2] <= 0.069519f)
        {
            if (q[6] <= -0.500000f)
            {
                return false;
            }
            else
            {
                return false;
            }
        }
        else
        {
            if (q[0] <= 0.299521f)
            {
                if (q[3] <= 0.239131f)
                {
                    return false;
                }
                else
                {
                    if (q[7] <= 0.403302f)
                    {
                        return true;
                    }
                    else
                    {
                        return false;
                    }
                }
            }
            else
            {
                if (q[10] <= 0.500000f)
                {
                    return false;
                }
                else
                {
                    return false;
                }
            }
        }
    }
}
