#!/usr/bin/env python3
"""Emit src/Api/Scorers/Cascade.cs from cascade/tree.json.

Generates an if/else cascade that returns (decided, score):
  - decided=true,  score=0.0f → committed legitimate (not fraud).
  - decided=true,  score=1.0f → committed fraud.
  - decided=false, score=0.0f → leaf is impure or unknown → fall through to IvfScorer.

Score values 0.0/1.0 chosen so they cleanly satisfy the bench's `score < 0.6f` cutoff.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TREE = ROOT / "cascade" / "tree.json"
OUT  = ROOT / "src" / "Api" / "Scorers" / "Cascade.cs"

# Map our 22-feature index → expression that retrieves the value at runtime.
# 0..13: query[i]
# 14..16: top3Cells[0..2]  (cast to float for tree comparison)
# 17..19: top3Dists[0..2]
# 20:    d_gap  = top3Dists[1] - top3Dists[0]
# 21:    d_ratio= top3Dists[1] > 0 ? top3Dists[0]/top3Dists[1] : 1f
def feature_expr(idx):
    if idx < 14:
        return f"query[{idx}]"
    if idx < 17:
        return f"(float)top3Cells[{idx - 14}]"
    if idx < 20:
        return f"top3Dists[{idx - 17}]"
    if idx == 20:
        return "(top3Dists[1] - top3Dists[0])"
    if idx == 21:
        return "(top3Dists[1] > 0f ? top3Dists[0] / top3Dists[1] : 1f)"
    raise ValueError(idx)


def main():
    payload = json.loads(TREE.read_text())
    nodes = {n["node_id"]: n for n in payload["nodes"]}
    n_leaves = payload["n_leaves"]
    purity = payload["purity_threshold"]
    decided_leaves = sum(1 for n in payload["nodes"]
                         if n["is_leaf"] and n["decided"])

    lines = []
    indent = lambda lvl: "    " * lvl

    def emit(node_id, lvl):
        n = nodes[node_id]
        if n["is_leaf"]:
            if n["decided"]:
                # Committed: return the predicted class as 0f or 1f.
                score = "1f" if n["pred"] == 1 else "0f"
                comment = (f"// leaf {n['node_id']}: n={n['n']} purity={n['purity']:.3f}"
                           f" pred={'fraud' if n['pred']==1 else 'legit'}")
                lines.append(f"{indent(lvl)}{comment}")
                lines.append(f"{indent(lvl)}return (true, {score});")
            else:
                comment = (f"// leaf {n['node_id']}: n={n['n']} purity={n['purity']:.3f}"
                           f" REJECT → IvfScorer fallback")
                lines.append(f"{indent(lvl)}{comment}")
                lines.append(f"{indent(lvl)}return (false, 0f);")
            return
        expr = feature_expr(n["feature_idx"])
        thr = n["threshold"]
        # sklearn rule: x <= threshold goes LEFT.
        lines.append(f"{indent(lvl)}if ({expr} <= {thr:.7f}f)")
        lines.append(f"{indent(lvl)}{{")
        emit(n["left"], lvl + 1)
        lines.append(f"{indent(lvl)}}}")
        lines.append(f"{indent(lvl)}else")
        lines.append(f"{indent(lvl)}{{")
        emit(n["right"], lvl + 1)
        lines.append(f"{indent(lvl)}}}")

    emit(0, 2)  # body indent (inside method)

    body = "\n".join(lines)
    src = f"""// <auto-generated>
//   Generated by tools/cascade_emit.py from cascade/tree.json.
//   Do not edit by hand.
//   Stats: depth={payload['max_depth']} leaves={n_leaves} decided={decided_leaves} purity_threshold={purity}.
// </auto-generated>
using System;

namespace Rinha.Api.Scorers;

public static class Cascade
{{
    /// <summary>
    /// Pre-classifies a query before the IVF scorer. Returns (decided, score):
    ///   decided=true  → cascade committed; use the returned score directly.
    ///   decided=false → query landed in a rejected leaf; caller must fall through
    ///                   to the full IvfScorer.
    /// </summary>
    /// <param name="query">14-dim normalized query vector.</param>
    /// <param name="top3Cells">IDs of the 3 nearest IVF centroids (sorted ascending by distance).</param>
    /// <param name="top3Dists">Squared L2 distances to those 3 centroids.</param>
    public static (bool decided, float score) TryDecide(
        ReadOnlySpan<float> query,
        ReadOnlySpan<int>   top3Cells,
        ReadOnlySpan<float> top3Dists)
    {{
{body}
    }}
}}
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(src)
    print(f"wrote {OUT}  ({OUT.stat().st_size} bytes)")
    print(f"  depth={payload['max_depth']}, leaves={n_leaves}, "
          f"decided={decided_leaves}, purity_threshold={purity}")


if __name__ == "__main__":
    main()
