#!/usr/bin/env python3
"""J24: train hard-query predictor.

Reads CSVs in tools/hq-data/, label = (earlyStopMode == 0) -> "hard" (full scan).
Trains a small DecisionTree, prints stats, and emits a C# cascade in
src/Api/Scorers/HardQueryClassifier.g.cs.

Run:  .venv/bin/python tools/train_hard_query.py
"""
import glob, sys
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier, _tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

CSV_GLOB = "tools/hq-data/hq-*.csv"
OUT_CS = "src/Api/Scorers/HardQueryClassifier.g.cs"
N_FEAT = 14
COLS = [f"f{i}" for i in range(N_FEAT)] + ["rows", "mode"]

def main():
    files = sorted(glob.glob(CSV_GLOB))
    if not files:
        print(f"No CSVs at {CSV_GLOB}", file=sys.stderr); sys.exit(1)
    dfs = [pd.read_csv(f, header=None, names=COLS) for f in files]
    df = pd.concat(dfs, ignore_index=True)
    print(f"Loaded {len(df):,} samples from {len(files)} files")
    print(f"  mode hist: {df['mode'].value_counts().to_dict()}")

    # Hard = mode 0 (full scan, no early stop). Heaviest queries.
    df["hard"] = (df["mode"] == 0).astype(int)
    hard_rate = df["hard"].mean()
    print(f"  hard rate: {hard_rate:.3%}")
    if hard_rate < 0.005 or hard_rate > 0.5:
        print(f"  WARN: extreme class balance, predictor may be useless")

    X = df[[f"f{i}" for i in range(N_FEAT)]].values
    y = df["hard"].values

    X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

    # Sweep depth, pick best macro-F1 on test.
    best = None
    for d in [3, 4, 5, 6, 7, 8]:
        clf = DecisionTreeClassifier(max_depth=d, min_samples_leaf=200,
                                     class_weight="balanced", random_state=42)
        clf.fit(X_tr, y_tr)
        score = clf.score(X_te, y_te)
        # also recall on hard class — we want HIGH recall on hard (catch them)
        pred = clf.predict(X_te)
        from sklearn.metrics import precision_score, recall_score, f1_score
        prec = precision_score(y_te, pred, zero_division=0)
        rec = recall_score(y_te, pred, zero_division=0)
        f1  = f1_score(y_te, pred, zero_division=0)
        nleaves = clf.get_n_leaves()
        print(f"  depth={d}: acc={score:.3f} hard_prec={prec:.3f} hard_rec={rec:.3f} hard_f1={f1:.3f} leaves={nleaves}")
        if best is None or f1 > best[0]:
            best = (f1, d, clf, prec, rec)

    f1, depth, clf, prec, rec = best
    print(f"\nPicked depth={depth} f1={f1:.3f} prec={prec:.3f} rec={rec:.3f}")
    print(confusion_matrix(y_te, clf.predict(X_te)))

    emit_cs(clf, depth, prec, rec, f1, hard_rate)
    print(f"Wrote {OUT_CS}")


def emit_cs(clf, depth, prec, rec, f1, hard_rate):
    """Emit a tiny if-tree C# classifier."""
    tree = clf.tree_
    feat = tree.feature
    thr = tree.threshold
    left = tree.children_left
    right = tree.children_right
    value = tree.value  # shape (n_nodes, 1, 2): [n_easy, n_hard]

    lines = [
        "// <auto-generated>",
        "// Generated by tools/train_hard_query.py — DO NOT EDIT.",
        f"// depth={depth} hard_rate={hard_rate:.3%} hard_prec={prec:.3f} hard_rec={rec:.3f} f1={f1:.3f}",
        "// </auto-generated>",
        "namespace Rinha.Api.Scorers;",
        "",
        "internal static class HardQueryClassifier",
        "{",
        "    public static bool IsHard(System.ReadOnlySpan<float> q)",
        "    {",
    ]

    def emit(node, indent):
        pad = "    " * indent
        if left[node] == _tree.TREE_LEAF:
            v = value[node][0]
            # Class 1 = hard. Predict hard if hard count > easy count (class_weight=balanced
            # already shifted these counts).
            is_hard = bool(v[1] >= v[0])
            lines.append(f"{pad}return {str(is_hard).lower()};")
            return
        f = int(feat[node])
        t = float(thr[node])
        lines.append(f"{pad}if (q[{f}] <= {t:.6f}f)")
        lines.append(f"{pad}{{")
        emit(int(left[node]), indent + 1)
        lines.append(f"{pad}}}")
        lines.append(f"{pad}else")
        lines.append(f"{pad}{{")
        emit(int(right[node]), indent + 1)
        lines.append(f"{pad}}}")

    emit(0, 2)
    lines += ["    }", "}", ""]

    with open(OUT_CS, "w") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    main()
